url: https://www.ampyard.com

# Site settings
title: "Ampyard"
email: info@ampyard.com
description: "Agile | Technology | DevOps | Software"


# Team names, titles and social links
people:
- name: Kamal Raj Sekar
  pic: 1
  position: Lead Technology Consultant
  url: https://www.linkedin.com/in/kamalrajsekar/

- name: Vivek Ganesan
  pic: 2
  position: Agile / DevOps Consultant
  url: https://www.linkedin.com/in/vivganes/


# Postal address (add as many lines as necessary)
address:
  - line: Ampyard Private Limited, BHIVE Workspace, No.703, 22nd Main Road, HSR Layout, Sector 2
  - line: Bengaluru, Karnataka, 560102

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-font-awesome-sass
  - jekyll-sitemap
