url: https://www.ampyard.com

# Site settings
title: "Ampyard - Agile | Technology | DevOps | Software"
email: info@ampyard.com
description: "Ampyard - Agile | Technology | DevOps | Software"


# Team names, titles and social links
people:
- name: Kamal Raj Sekar
  pic: 1.jpg
  position: Lead Technology Consultant
  url: https://www.linkedin.com/in/kamalrajsekar/

- name: Vivek Ganesan
  pic: 2.jpg
  position: Agile / DevOps Consultant
  url: https://www.linkedin.com/in/vivganes/


- name: Akshay Sushir
  pic: 4.png
  position: Junior Software Engineer
  url: https://www.linkedin.com/in/akshay-sushir-280324119/

# Testimonials
testimonial:
  -
    givername: Gary Lawler
    company: Senior Developer
    linkedin: https://www.linkedin.com/in/gary-lawler-98252256
    content: >
      '"As technical lead in Greenfinch technology, I worked alongside Kamal for almost two years and feel confident in recommending him to your organisation.
      Kamal was instrumental in delivering a new notifications framework for the Etech project to a high technical standard while under considerable time pressure. At this time he
      demostrated leadership as well as technical skills by directing a small team to complete his design. The customer was delighted to have this functionality delivered on budget and to
      a high degree of quality. In customer-facing rolers, Kamal has distinguished himself with several clients. He has a calm and professional demeanour with an ability to elicit
      requirements from non-technical customers. He has gained the respect of both peers and management for an ability to articulate both challenges and associated solutions to ensure long-term
      project success. Design and planning come naturally to Kamal. As he matured into his role at Greenfinch he succeeded in adapting to increasingly greater responsibilities in these realms,
      ultimately being granted full care of the company's largest and most complex project. In his tenure at Greenfinch, Kamal has been a key figure in the success of the Etech project and
      in ensuring that the team as a whole remain focused and happy."'
    pic: ''
  -
    givername: Rupesh Gaur
    company: Societe Generale Global Solutions Centre
    linkedin: https://www.linkedin.com/in/rupesh-gaur-724b8124
    content: '"Vivek provided Agile@Scale consulting for my Tribe. He closely worked with my FT managers to coach them and their teams on Agile methodology and craftmanship. In addition he has taken many sessions on pair programming, Scrum management, sprint planning, product backlog, business demo and retrospectives. He has supported throughout the Agile@cale transformation of my tribe.

    It was not an easy task to Coach 9 Feature Teams and 5 component teams given that teams had to deliver critical regulatory projects like IFRS9 at the time of transformation. He has a ability to drive teams towards the target objectives.I remember he has followed rigorously with my managers to define KIPs and deliver the dashboard template.

    Vivek has passion and instinct for Agile which motivates him by itself and this reflects during his coaching.
    I worked with many Coaches on Agile since last 10 year including consultants (India &France) from top consulting companies and Vivek was one of the best among them. He has long way to go on his Agile journey and I wish best for him. Thank you Vivek for your contribution to make my Tribe successful in its transformation"'
    pic: ''
  -
    givername: Albert Sanuy Lostes
    company: New Relic, Inc.
    linkedin: https://www.linkedin.com/in/asanuy/
    content: >
      '"It was a great experience to be working with Kamal for roughly two years. During that time, he proved his accountable attitude and great skills to solve difficult architectural problems, provide solutions and help the teammates.
      His good mindset, experience and attitude to be up to date with technology makes him a great co-worker to be working with. "'
    pic: ''
  -
    givername: Andrei Rjabokon
    company: Full Stack Developer, RnD
    linkedin: https://www.linkedin.com/in/andreirjabokon/
    content: >
      '"I highly recommend Kamal to any business or team there is. Working with Kamal as a teammate was both pleasure and highly efficient experience, where he showed levels of professionalism I have never seen in anyone else. Focused on delivery of excellent quality product, not afraid to take on tasks of every possible scale, eager to share knowledge and ideas, honest, very friendly and open minded personality -
      all this can describe my experience with Kamal shortly, but nothing else as  pleasure, both professionally and socially. I can recommend Kamal as a highly valued asset to any team."'
    pic: ''
  -
    givername: Jennifer Conlon
    company: Optum
    linkedin: https://www.linkedin.com/in/jennifer-conlon/
    content: >
      '"I have worked with Kamal for over 4 years. From beginning to end he was someone I enjoyed working with for many reasons. Firstly technically he was always striving to better the products he was working on with passion. His teamwork was always to the forefront, constantly helping those around him and working to find solutions. His curiosity to improve and introduce improvements was constantly refreshing and
       he was just a great presence to work with. I know going forward he will continue to enhance any projects he is involved in and is a great asset to any project he is involved with. Leading from the front with passion and knowledge always."'
    pic: ''
# Postal address (add as many lines as necessary)
address:
  - line: Ampyard Private Limited, Bhive, NO. 148, BBMP NO. 170/148, 
  - line: 5TH Main Road Sector-6, HSR Layout, Bangalore, Karnataka - 560102

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-font-awesome-sass
  - jekyll-sitemap
