url: https://www.ampyard.com
baseurl: /

# Site settings
title: "Ampyard"
email: info@ampyard.com
description: "Welcome to Ampyard, get in touch for Agile | Technology | DevOps Consulting"


# Team names, titles and social links
people:
- name: Kamal Raj Sekar
  pic: 1
  position: Lead Technology Consultant
  
- name: Vivek Ganesan
  pic: 2
  position: Agile / DevOps Consultant
  

# Postal address (add as many lines as necessary)
address:
  - line: Ampyard Private Limited, BHIVE Workspace, No.703, 22nd Main Road, HSR Layout, Sector 2
  - line: Bengaluru, Karnataka, 560102

# Build settings
markdown: kramdown
permalink: pretty
